site_name: Self-sufficiency Wiki
site_description: Practical, printable sufficiency knowledge with clean cross-links.
site_url: https://example.org
repo_url: https://github.com/bl1tzkr13g/self-sufficiency-wiki
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      accent: lime
plugins:
  - search
  - awesome-pages
  - ezlinks:
      wikilinks: true   # enables [[Page]] links
  - obsidian-links:
      wikilinks: true
      markdown_extensions: true
  - roamlinks:
      wikilinks: true
  - glightbox
  - print-site:
      add_to_navigation: true
      print_page_title: "Print whole site"
      print_site_dir: print
extra_css:
  - styles/print.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Knowledge:
      - Animal Husbandry: animal_husbandry_index.md
      - Cookery:
          - Confections: confections_index.md
          - Drinks: drinks_index.md
          - Fats: fats_index.md
          - Foods: foods_index.md
          - Ingredients: ingredients_index.md
          - Preservation Techniques: preservation_techniques_index.md
          - Preserved Foods: preserved_foods_index.md
          - Utensils: utensil_index.md
      - Medicines: medicines_index.md
      - Plants: plants_foraging.md
      - Tinctures: tinctures_index.md
      - Tools: tools_index.md
      - Trees: trees_index.md

